# Generated by Django 4.1.6 on 2023-02-11 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeapp', '0002_cake_categori'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cake',
            name='categori',
        ),
        migrations.AddField(
            model_name='cake',
            name='categorivto',
            field=models.CharField(blank=True, choices=[('BIRTHDAY', 'BIRTHDAY'), ('WEDDING', 'WEDDING'), ('CUSTOM', 'CUSTOM')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Qatego',
        ),
    ]
