# Generated by Django 4.1.6 on 2023-02-12 23:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakeapp', '0003_remove_cake_categori_cake_categorivto_delete_qatego'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='big_descri',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
