# Generated by Django 4.1.6 on 2023-02-13 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeapp', '0005_comandformintemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comandformintemplate',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
