# Generated by Django 4.1.6 on 2023-02-13 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeapp', '0006_alter_comandformintemplate_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
