# Generated by Django 4.1.6 on 2023-02-13 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeapp', '0007_cake_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
