# Generated by Django 4.1.6 on 2023-02-13 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakeapp', '0011_contactsms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactsms',
            old_name='email',
            new_name='emaltext',
        ),
    ]
