# Generated by Django 4.1.6 on 2023-02-17 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cakeapp', '0012_rename_email_contactsms_emaltext'),
    ]

    operations = [
        migrations.AddField(
            model_name='comandformintemplate',
            name='cake',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='cakeapp.cake'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactchefform',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
